from praetor.actors.traits import Actor, AddressedEvent, MessageDispatcher
from praetor.core import Node


class InMemoryDispatcher[Command](MessageDispatcher[Command]):
    """Routes messages between actors in-process"""

    def __init__(self) -> None:
        """Create with an empty registry"""
        self._registry: dict[Node, Actor[AddressedEvent[Command]]] = {}

    def register(self, node: Node, actor: Actor[AddressedEvent[Command]]) -> None:
        """Registers an actor to receive messages"""
        self._registry[node] = actor

    def enqueue_messages(self, messages: list[AddressedEvent[Command]]) -> None:
        """Iterates over events generated by a node and puts them onto target queues."""
        for msg in messages:
            if msg.to:
                for target_node in msg.to:
                    self._registry[target_node].tell(msg)
