from abc import ABC, abstractmethod
from typing import Any

from pydantic import BaseModel

from praetor.core import Event, Node


class Actor[T](ABC):
    """Base class for an actor"""

    @abstractmethod
    def start(self) -> None:
        """Kick off the processing loop."""
        pass

    @abstractmethod
    async def stop(self) -> None:
        """Stop the actor"""
        pass

    @abstractmethod
    async def send(self, message: T) -> Any:
        """Give the actor something to do"""
        pass

    @abstractmethod
    def tell(self, message: T) -> None:
        """Fire-and-forget"""
        pass


class ActorSystem(ABC):
    """Owns the actors as a group so the caller starts and stops the cluster"""

    @abstractmethod
    def start(self) -> None:
        """Start every actor."""
        pass

    @abstractmethod
    async def stop(self) -> None:
        """Stop every actor"""
        pass


class MessageDispatcher[T](ABC):
    """Actor message delivery"""

    @abstractmethod
    def enqueue_messages(self, messages: list[AddressedEvent[T]]) -> None:
        """Iterates over events generated by a node and puts them onto target queues."""
        pass

    @abstractmethod
    def register(self, node: Node, actor: Actor[AddressedEvent[T]]) -> None:
        """Registers an actor to receive messages"""
        pass


class AddressedEvent[Command](BaseModel):
    """An event plus who it's for."""

    event: Event[Command]
    to: frozenset[Node]
